### ISSUE TITLE
pls upgrade the virtualbox guest version

### ISSUE THREAD

**Issue by alexwhen** [AntonioMeireles/boot2docker-vagrant-box#1]
=> default: Machine booted and ready!
GuestAdditions versions on your host (4.3.22) and guest (4.3.20 r96996) do not match.
The guest's platform is currently not supported, will try generic Linux method...
Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Installing Virtualbox Guest Additions 4.3.22 - guest version is 4.3.20 r96996
mkdir: can't create directory '/tmp/selfgz137014945': No such file or directory
Cannot create target directory /tmp/selfgz137014945
You should try option --target OtherDirectory
An error occurred during installation of VirtualBox Guest Additions 4.3.22. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.

**Comment by alexwhen** [comment]
the port forwarding doesn't work

**Comment by AntonioMeireles** [comment]
@litrue i consume plain upstream boot2docker refactoring it to make it a 1st class Vagrant citizen. the issue you hit is actually an upstream one. the good news is that 1.6 is already in release candidate stage and near release...

**Comment by AntonioMeireles** [comment]
fwiw @litrue **if** boot2docker releases an update to their 1.5 stream (to fix this) while 1.6 is not out  i'll push it to 'my' side asap.

**Comment by alexwhen** [comment]
thank you very much

**Comment by AntonioMeireles** [comment]
@litrue just pushed the _vagrantified_ **1.6.0** **boot2docker** to [Vagrant's Atlas](https://atlas.hashicorp.com/AntonioMeireles/boxes/boot2docker-vagrant-box). Can you please give it a try and give feedback. AFAICT it should fix your issue :smile:

**Comment by alexwhen** [comment]
fixed,thank you very much

**Comment by AntonioMeireles** [comment]
@litrue great to hear! hope you are enjoying it :smile:
